version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snotel-weather-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13l80bogsksw7"
s3_prefix = "snotel-weather-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
